1. import libraries and and dataset - no need to change
```{r, message=FALSE, warning=FALSE}
#library(tidyverse)
library(tidyverse)
library(readxl)
library(ggplot2)
library(dplyr)
library(plotly)
library(ggseas)
library(chron)
data <- read_csv("covid.com.csv") %>% 
  select(c(-1))
```


2. preprocess data - no need to change
```{r}

# add number line
data$dummy <- -10


# change category events name
# group event categories into easing/lifting and imposing
group_event_catg <- function(x){
  new_col = c()
  check = substr(x, nchar(x), nchar(x))
  if (is.na(check)){
    new_col <- append(new_col, x)
  } else if(check %in% c("M","A","I")){
    new_col <- append(new_col, "Mandatory")
  } else if (check == "R"){
    new_col <- append(new_col, "Re-Issued")
  } else if (check == "E"){
    new_col <- append(new_col, "Eased")
  } else if (check == "L"){
    new_col <- append(new_col, "Lifted ")
  } 
}
data$event_MELR <- sapply(data$EVENT_CATG_S,
                                    FUN=group_event_catg)
# category num
big_catg <- function(x){
  new_col = c()
  if (is.na(x)){
    new_col <- append(new_col, x)
  } 
  else if(x=="15M"){
    new_col <- append(new_col, "Face \n Covering")
  } else if(grepl("2", x)){
    new_col <- append(new_col, "Business \n Restrictions")
  } else if(grepl("3", x)){
    new_col <- append(new_col, "Indoor Gathering \n Restrictions")
  } else if(grepl("4", x)){
    new_col <- append(new_col, "Restaurant/Bar \n Restrictions")
  } else{
    new_col <- append(new_col, "Stay at \n Home Orders")
  }
}

data$big_cat <- sapply(data$EVENT_CATG_S, FUN=big_catg)
data$event <- paste(data$big_cat, "\n", data$event_MELR)
data$event[data$event=="NA \n NA"] <- NA



# text color bins
bins <- c(-Inf,0,0.25,0.75,1.20,1.55,1.85,2.10,2.35,2.70,3.05,3.40,3.75,
          4.00, 5.00)
data$color_scale <- cut(data$SCORE, breaks=bins)
color_v <- c("#ffffff","#fdfec0", "#fdffa3","#ffd799", "#ffb078","#fc8861",
             "#f2615d","#d8466c","#87377a","#942c81","#721f82","#51127c",
             "#2d1160","#ffd3d1","#100c2E")

data$event <- as.factor(data$event)
color_event_v <- c("Business \n Restrictions \n Eased"="#839c6d",
                   "Business \n Restrictions \n Lifted "="#608341",
                   "Business \n Restrictions \n Mandatory"="#f2534e",
                   "Business \n Restrictions \n Re-Issued"="#f53731",
                   "Face \n Covering \n Mandatory"="#db211a",
                   "Indoor Gathering \n Restrictions \n Eased"="#b9db97",
                   "Indoor Gathering \n Restrictions \n Lifted"="#9CBA7F",
                   "Indoor Gathering \n Restrictions \n Mandatory"="#bf1b15",
                  "Indoor Gathering \n Restrictions \n Re-Issued"="#ad1711",
                  "Restaurant/Bar \n Restrictions \n Eased"="#8BA870",
                  "Restaurant/Bar \n Restrictions \n Lifted"="#677d52",
                  "Restaurant/Bar \n Restrictions \n Mandatory"="#c90902",
                  "Restaurant/Bar \n Restrictions \n Re-Issued"="#a60903",
                  "Stay at \n Home Orders \n Lifted"="#8dbd77",
                  "Stay at \n Home Orders \n Mandatory"="#e05651")

names(color_event_v) = levels(as.factor(data$event))
names(color_v) = levels(data$color_scale)


text_y_pos <- function(state_event, days_diff, space_decs,
                       label_position_offset){
  y_pos_vec = c(max(state_event[,9])+label_position_offset)
  for (i in 2:nrow(state_event)){
    diff = state_event[i,3] - state_event[i-1,3]
    if (as.integer(diff)<days_diff){
      tmp = y_pos_vec[i-1]-space_decs
       y_pos_vec = append(y_pos_vec, tmp)
    } else {
      y_pos_vec = append(y_pos_vec, max(state_event[,9])+label_position_offset)
    }
  }
  return(y_pos_vec)
}

```


3. Create an interactive version for the time trend - no need to change
```{r, message=FALSE, warning=FALSE}

plot_time_interact <- function(sstate, window_num, days_diff, space_desc,
                   label_position_offset, y_axis_max,
                   no_score_legend_lower, no_score_legend_upper){
  state_data <- data[data$STATE==state,]
  state_event <- na.omit(state_data[!is.na(state_data$EVENT_CATG_S),])
  state_event_date <- state_event$DATE
  state_event$txt_y <- text_y_pos(state_event, days_diff, space_decs,
                       label_position_offset)
  state_event$event2 <- state_event$event
  plot3 <- ggplot(state_data, aes(DATE, NEWCD_NORM_500,
                                  Date=DATE, New_Cases=NEWCD_NORM_500)) + 
    geom_point(size=2, alpha=1) + 
    stat_rollapplyr(width = window_num, align = "right", size = 2,
                    col="gray", alpha=1)+
    geom_point(mapping=aes(x=DATE, y=dummy, fill=color_scale, score=SCORE),
               shape=22, size=2, color="transparent")+
    scale_fill_manual(values=color_v, name="")+
    scale_color_manual(values=color_event_v, name="")+
    geom_vline(data=state_event,
               aes(xintercept=as.numeric(DATE), color=event), 
               linetype="dotted")+
    geom_text(data=state_event,
               aes(x=DATE, y=txt_y, color=event, label=as.character(event),
                   Event=event), size=3)+
    ylim(-15, y_axis_max)+
    theme(legend.title=element_blank())+
    theme_bw()+
    labs(x = "Months", y = "New Daily Cases Normalized")+
    scale_x_date(date_breaks = "months" , date_labels = "%b")+
    ggtitle(paste(state, ",","Average Window = ", window_num)) 
    
  myplot <- ggplotly(plot3,
                     tooltip=c("Date", "New_Cases", "Event","score")) %>% 
    layout(legend=list(title=list(text='<b> Orders</b>')))
  
  myplot<- style(myplot, showlegend = FALSE,
                 traces=c(no_score_legend_lower:no_score_legend_upper))
  
  for (i in 1:length(myplot$x$data)){
    if (!is.null(myplot$x$data[[i]]$name)){
        myplot$x$data[[i]]$name = 
          gsub("\\(","",str_split(myplot$x$data[[i]]$name,",")[[1]][1])
    }
}
  myplot

}

```


***** 4. run interactive time series plot with specified state and window
change variables for different states, moving average window, and aesthetic
```{r, message=FALSE, warning=FALSE}
# identify which individual state
state = "FLORIDA"
# identify the window(days) for moving averages
window_num = 7

# the next four variables are for aesthetic only 
# changing these variables can lesson the problems of text overlapping

# if days_diff is too small, all the neighboring intervention texts will overlap
days_diff = 15
# identify how much we want to separate this intervention text from last
# intervention text
space_decs = 45
# y position of highest text label
label_position_offset = 450
# y axis max height
y_axis_max = 500
no_score_legend_lower = 1
no_score_legend_upper = 8

# function to plog interactive time series - no need to change

plot_time_interact(state, window_num, days_diff, space_desc,
                   label_position_offset, y_axis_max,
                   no_score_legend_lower, no_score_legend_upper)
#htmlwidgets::saveWidget(as_widget(p), "FL_interactive.html")
```