---
title: "Undergrad research"
authors: "Alvin Pan"
Andrew IDs: "qpan"
output:
  pdf_document:
    toc: no
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
---
```{r}
library("readxl")
library(tidyverse)
```



```{r}
covid = data.frame(read_excel("covid1.xlsx"))
covid.g1 = data.frame(read_excel("COVID_G1.xlsx"))
```

unify date syntax
```{r}
covid$DATE = as.Date(covid$DATE)
```

```{r}
covid.g1$DATE = as.Date(parse_date_time(covid.g1$DATE, orders="mdy"))
```

combine 2 data frames
```{r}
covid.com = covid %>% full_join(covid.g1, by = c("STATE", "DATE"))
```


```{r}
#function to union 2 feature vectors
combine.attributes <- function(x, y) {
  n = length(x)
  for (i in 1:n) {
    if (is.na(x[i])) {
      x[i] = y[i]
    }
  }
  return (x)
}
```


```{r}
#function to union duplicate features
clean.combined.data <- function(data, attrs) {
  for (name in attrs) {
    data[, name] = combine.attributes(covid.com[, paste(name, ".x", sep="")], covid.com[, paste(name, ".y", sep="")])
    data[, paste(name, ".x", sep="")] = NULL
    data[, paste(name, ".y", sep="")] = NULL
  }
  return (data)
}
```


```{r}
#function to fill the NAs with the most recently observed non-NA for all input features of data frame
extend.attr <- function(data, features) {
  n = dim(data)[1]
  for (feature in features) {
    xs = rep(0, n)
    index = 1
    while (is.na(data[,feature][index])) {index = index + 1}
    curr.x = 0
    while (index < n+1) {
      if (!(is.na(data[,feature][index]))) {
        curr.x = data[,feature][index]
      }
      xs[index] = curr.x
      index = index + 1
    }
    return (data)
  }
}
```

```{r}
# extract top n states with the most people
top_pop_states <- function(data, n=5) {
  d = data %>% group_by(STATE) %>% summarize(POPULATION = mean(POPULATION, na.rm = TRUE))
  return (top_n(d, n=n, wt=POPULATION)[[1]])                          
}
```


```{r}
# plot covid cases for top population states
plot_states <- function(data, states, feature, x=2, y=3) {
  # top_states = top_pop_states(covid, n)
  par(mfrow=c(x,y), mar=c(4,4,2,0.5)) # Setup grid, margins
  for (state in states) {
    d = data %>% filter(STATE == state) %>% select(POPULATION, DATE, NEWCONFIRMED, CUMCONFIRMED, NEWDEATHS, CUMDEATHS, SCORE)
    plot(d$DATE, d[,feature], xlab = "Time", ylab = feature, main = paste("COVID cases in", state), pch = 20, cex = 0.5)
  }
}
```


```{r}
duplicated.attributes = c("STUSAB", "LATITUDE", "LONGITUDE", "STATEFP", "GNISID")
```

```{r}
covid.com = clean.combined.data(covid.com, duplicated.attributes)
```

```{r}
covid.com = extend.attr(covid.com, c("SCORE"))
```

```{r}
head(covid.com, 10)
```


---------below are just random experiments


```{r}
plot(covid.com$DATE, covid.com$SCORE)
```


```{r}
cont.cols = c(5:11,14:17)
```



```{r}
par(mfrow=c(3,4), mar=c(4,4,2,0.5)) # Setup grid, margins
for (j in cont.cols) {
  hist(covid[,j], xlab=colnames(covid)[j],
       main=paste("Hist of", colnames(covid)[j]),
       col="lightblue", breaks=20)
}
```


```{r}
grouped.df = covid %>% group_by(STATE) %>% summarize(POPULATION = sum(sqrt(POPULATION), na.rm = TRUE), NEWCONFIRMED = sum(log(NEWCONFIRMED+1), na.rm = TRUE), CUMCONFIRMED = sum(log(CUMCONFIRMED+1), na.rm = TRUE), NEWDEATHS=sum(log(NEWDEATHS+1), na.rm = TRUE), CUMDEATHS=sum(log(CUMDEATHS+1), na.rm = TRUE)) %>% data.frame()
```

```{r}
grouped.df
```


```{r}
par(mfrow=c(2,3), mar=c(4,4,2,0.5)) # Setup grid, margins
for (j in (2:6)) {
  hist(grouped.df[,j], xlab=colnames(grouped.df)[j],
       main=paste("Hist of", colnames(grouped.df)[j]),
       col="lightblue", breaks=20)
}
```



```{r}
head(covid.com)
```


```{r}
states = top_pop_states(covid)
plot_states(covid.com, states, 'SCORE')
```


```{r}
plot_states(covid, 'NEWCONFIRMED')
```


```{r}
write.csv(covid.com, "covid.com.csv")
```

