import library
```{r}
library(tidyverse)
library(readxl)
library(plotly)
library(zoo)
```

import data
```{r}
variant <- read_excel("B.1.1.7 Lineage Report UK.xlsx")
variant$date <- as.Date(variant$date, format="%Y-%m-%d")
variant$proportion <- variant$proportion*100
```

```{r}
dt <- read_excel("UKbyAge_Groupedx6.xlsx") %>% 
  na.omit()

dt$date <- as.Date(dt$date, format="%Y-%m-%d")
dt$rolling_avg <- rollmean(dt$`00_90+`, k=7, fill=NA)
may1 <- as.Date("2020-05-01", format="%Y-%m-%d")
dt <- dt[dt$date>=may1,] %>% 
  select(c(1,6:13))

# calculate percentage 
#dt$total <- rowSums(dt[,-c(1,)])
dt$`00_04/total(%)` <- round(dt$`00_04`/dt$`00_90+`*100,2)
dt$`05_14/total(%)` <- round(dt$`05_14`/dt$`00_90+`*100,2)
dt$`15_24/total(%)` <- round(dt$`15_24`/dt$`00_90+`*100,2)
dt$`25_39/total(%)` <- round(dt$`25_39`/dt$`00_90+`*100,2)
dt$`40_59/total(%)` <- round(dt$`40_59`/dt$`00_90+`*100,2)
dt$`60_90+/total(%)` <- round(dt$`60_90+`/dt$`00_90+`*100,2)
```


interactive with plotly
```{r}
ay <- list(
  tickfont = list(color = "black"),
  overlaying = "y",
  side = "right",
  title = "Total New Daily Cases"
)

fig <- plot_ly()

fig <- fig %>% 
  add_trace(data=dt, x=~date, y=~`40_59/total(%)`,
            type='bar', name = "40-59 Years", visible="legendonly",
            marker=list(color="#35b5b1"))
fig <- fig %>% 
  add_trace(data=dt, x=~date, y=~`25_39/total(%)`,
            type='bar', name = "25-39 Years", visible="legendonly",
            marker=list(color="#abc451"))
fig <- fig %>% 
  add_trace(data=dt, x=~date, y=~`60_90+/total(%)`,
            type='bar', name = "60-90+ Year", visible="legendonly",
            marker=list(color="#facb55"))

fig <- fig %>% 
  add_trace(data=dt, x=~date, y=~`15_24/total(%)`,
            type='bar', name = "15-24 Years", visible="legendonly",
            marker=list(color="#f2615d"))


fig <- fig %>% 
  add_trace(data=dt, x=~date, y=~`05_14/total(%)`,
            type='bar', name = "5-14 Years", visible="legendonly",
            marker=list(color="#942C81"))

fig <- fig %>% 
  add_trace(data=dt, x=~date, y=~`00_04/total(%)`,
            type='bar', name = "0-4 Years", visible="legendonly",
            marker=list(color="#2D1160"))


fig <- fig %>% 
  add_lines(data=dt, x=~date, y=~rolling_avg, name = "Total Cases",  yaxis = "y2",
            line = list(color = 'black'))

fig <- fig %>% 
  add_lines(data=variant, x=~date, y=~proportion, name="B117 variant",
            line=list(color='#a8a8a8'))

fig <- fig %>% layout(
    title = "Total COVID-19 Daily Cases in the UK and % of Daily Cases by Age Groups May 2020-Feburary 2021",
    yaxis2 = ay,
    yaxis = list(title="% of Daily Cases by Age Groups",
                 range=c(0, 100)),
    xaxis = list(title="Date",
                 type = 'date', tickformat = "%b %Y"),
    legend = list(x=1.1,
                  title=list(text='<b> Click to Select Groups </b>'),
                  traceorder="grouped"),
    barmode = 'overlay'
  )

fig
#p <- plot_ly(data=dt, x=~date, y=~`00_90+`, type='scatter',mode='lines')
#p
```

