1. import libraries and and dataset
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(ggplot2)
library(dplyr)
library(plotly)
library(ggseas)
library(chron)

data <- read.csv("covid.com.csv",
                 colClasses = "character") %>% 
  select(c(2,3,4,9:12,17,18,19,20,21,22,23,24,25))

county_dt <- read.csv("USA_Counties_Data.csv",
                      colClasses = "character") %>% 
  select(c(2,3,7))

k12_dt <- read_excel("k-12.xlsx") %>% 
  filter(.[,"EVENT_CATG"]!="15DM")

```


2. preprocess data
```{r}
# add number line
data$dummy <- -10

# change cols format
data$DATE <- as.Date(data$DATE)
k12_dt$DATE <- as.Date(k12_dt$DATE)

for (i in c(4:12,15)){
  data[,i]<- as.numeric(data[,i])
}

county_dt$POPULATION.2017. <- as.numeric(county_dt$POPULATION.2017.)
# change county data to all caps
county_dt$NAME <- toupper(county_dt$NAME)
county_dt$STATE_NAME <- toupper(county_dt$STATE_NAME)
colnames(county_dt) <- c("COUNTY","STATE", "POPULATION")

data <- inner_join(data, county_dt, by=c("COUNTY", "STATE")) 

# event label for school
k12_dt$event_label <- "K-12"
k12_dt$event_label <- as.factor(k12_dt$event_label)
k12_dt$DATE <- as.Date(k12_dt$DATE)
```

rescale data
```{r}
data$CUMCD_NORM_500 <- round(data$CUMCONFIRMED/(data$POPULATION/50000))
data$NEWCD_NORM_500 <- round(data$NEWCONFIRMED/(data$POPULATION/50000))
data$CUMDEATHS_NORM_500 <- round(data$CUMDEATHS/(data$POPULATION/50000))
data$NEWDEATHS_NORM_500 <- round(data$NEWDEATHS/(data$POPULATION/50000))
```


```{r}
# change category events name
# group event categories into easing/lifting and imposing
group_event_catg <- function(x){
  new_col = c()
  check = substr(x, nchar(x), nchar(x))
  if (is.na(check)){
    new_col <- append(new_col, x)
  } else if(check == "M"){
    new_col <- append(new_col, "Mandatory")
  } else if (check == "R"){
    new_col <- append(new_col, "Re-Issued")
  } else if (check == "E"){
    new_col <- append(new_col, "Eased")
  } else if (check == "L"){
    new_col <- append(new_col, "Lifted ")
  } else {
    new_col <- append(new_col, "Mandatory")
  }
}

data$event_MELR <- sapply(data$EVENT_CATG, FUN=group_event_catg)


# category number
big_catg <- function(x){
  new_col = c()
  if (is.na(x)){
    new_col <- append(new_col, x)
  } 
  else if(x %in% c("15COM","15CYM","15M2","15M3")){
    new_col <- append(new_col, "Face \n Covering")
  } else if(grepl("2", x)){
    new_col <- append(new_col, "Business \n Restrictions")
  } else if(grepl("3", x)){
    new_col <- append(new_col, "Indoor Gathering \n Restrictions")
  } else if(grepl("4", x)){
    new_col <- append(new_col, "Restaurant/Bar \n Restrictions")
  } else{
    new_col <- append(new_col, "Stay at Home \n Orders")
  }
}

data$big_cat <- sapply(data$EVENT_CATG, FUN=big_catg)
data$event <- paste(data$big_cat, "\n", data$event_MELR)
data$event[data$event=="NA \n NA"] <- NA

```
```{r}
# score bins and assign color
bins <- c(-Inf,0,0.25,0.75,1.20,1.55,1.85,2.10,2.35,2.70,3.05,3.40,3.75,
          4.00, 5.00)
data$color_scale <- cut(data$SCORE, breaks=bins)
color_v <- c("#ffffff","#fdfec0", "#fdffa3","#ffd799", "#ffb078","#fc8861",
             "#f2615d",
             "#d8466c","#87377a","#942c81","#721f82","#51127c", "#2d1160",
             "#ffd3d1")
names(color_v) = levels(data$color_scale)

# change color scale
data$event <- as.factor(data$event)
color_event_v <- c("Business \n Restrictions \n Eased"="#C0D9Af",
                   "Business \n Restrictions \n Lifted "="#608341",
                   "Business \n Restrictions \n Mandatory"="#f2534e",
                   "Business \n Restrictions \n Re-Issued"="#f53731",
                   "Face \n Covering \n Mandatory"="#db211a",
                   "Indoor Gathering \n Restrictions \n Eased"="#9CBA7F",
                   "Indoor Gathering \n Restrictions \n Mandatory"="#bf1b15",
                  "Indoor Gathering \n Restrictions \n Re-Issued"="#ad1711",
                  "Restaurant/Bar \n Restrictions \n Eased"="#8BA870",
                  "Restaurant/Bar \n Restrictions \n Mandatory"="#c90902",
                  "Restaurant/Bar \n Restrictions \n Re-Issued"="#a60903",
                  "K-12"="black")

text_y_pos <- function(ct_data, ct_event, days_diff, space_decs,
                       label_position_offset){
  y_pos_vec = c(max(ct_data[,8], na.rm=TRUE)+label_position_offset)
  for (i in 2:nrow(ct_event)){
    diff = ct_event[i,3] - ct_event[i-1,3]
    if (as.integer(diff)<days_diff){
      tmp = y_pos_vec[i-1]-space_decs
       y_pos_vec = append(y_pos_vec, tmp)
    } else {
      y_pos_vec = append(y_pos_vec, max(ct_data[,8],
                                        na.rm=TRUE)+label_position_offset)
    }
  }
  return(y_pos_vec)
}

```


3. Create an interactive version for the time trend
```{r, message=FALSE, warning=FALSE}

plot_time_interact <- function(state, county, window_num, days_diff, space_desc,
                   label_position_offset, y_axis_max, k12_text_y){
  ct_data <- data[data$STATE==state & data$COUNTY==county,]
  ct_event <- ct_data[!is.na(ct_data$EVENT_CATG),]
  ct_event_date <- ct_event$DATE
  ct_event$txt_y <- text_y_pos(ct_data, ct_event, days_diff, space_desc,
                       label_position_offset)
  
  ct_k12 <- k12_dt[k12_dt$STATE==state & k12_dt$COUNTY==county,]
  ct_k12$txt_y <- rep(k12_text_y, nrow(ct_k12))

  
  plot3 <- ggplot(ct_data, aes(DATE, NEWCD_NORM_500)) + 
    geom_point(aes(Date=DATE, New_Cases=NEWCD_NORM_500), size=2, alpha=1) + 
    stat_rollapplyr(width = window_num, align = "right", size = 1.5,
                    col="gray", alpha=1)+
    geom_vline(data=ct_k12, aes(xintercept=as.numeric(DATE), color=event_label),
               linetype="dotted")+
    geom_text(data=ct_k12, aes(x=DATE, y=txt_y, color=event_label,
                               label=as.character(event_label),
                               descript=SHORT_DESCRIPT),
              size=3)+
    geom_vline(data=ct_event,
               aes(xintercept=as.numeric(DATE), color=event), 
               linetype="dotted")+
    geom_text(data=ct_event, aes(x=DATE, y=txt_y, color=event, Date=DATE,
                                 label=as.character(event),
                                 descript=SHORT_DESCRIPT),
              size=3)+
    scale_color_manual(values=color_event_v)+
    geom_point(mapping=aes(x=DATE, y=dummy, fill=color_scale, score=SCORE),
               shape=22, size=2, color="transparent")+
    scale_fill_manual(values=color_v)+
    ylim(-10, y_axis_max)+
    theme(legend.title=element_blank())+
    labs(x = "Months", y = "New Daily Cases Normalized",
         title = paste(str_to_title(county), ",",str_to_title(state),",",
                      "County Population = ", ct_data$POPULATION, ",",
                      window_num, "Days Rolling Average"))+
    scale_x_date(date_breaks = "months" , date_labels = "%b")+
    theme_bw()
    
  p1 <- ggplotly(plot3, tooltip=c("Date", "New_Cases", "descript","score")) %>%
    layout(legend=list(title=list(text='<b> Event</b>')))
  p1


}

                

```


**** 4. run interactive time series plot with specified state and window
```{r, message=FALSE, warning=FALSE}
state = "IOWA"
county = "STORY"
window_num = 7
days_diff = 10
space_desc = 10
label_position_offset = 0
y_axis_max = 80
k12_text_y = 60
plot_time_interact(state, county, window_num, days_diff, space_desc,
                   label_position_offset, y_axis_max,k12_text_y)
```