

```{r, message=FALSE, warning=FALSE, echo = FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(readr)
library(ggfortify)
library(ggseas)
library(plotly)
library(zoo)
```

## States Mask Order

```{r, message=FALSE, warning=FALSE, echo = FALSE}
# select state, date, event_catg_s, score, newcd_norm_599
oldData <- read_csv("covid.com.csv") %>% 
  select(c(2, 4:5, 18)) 

# 15M stands for Mandatory Mask/Facecover Order
# See README of COVID_ALL_G1.xlsx
#head(data[!is.na(data$EVENT_CATG_S) & data$EVENT_CATG_S == "15M",])

data <- read_csv("State_Cases_G1_Merged_01112021.csv") %>% 
  select(c("STATE","DATE","NEWCONFIRMED", "SCORE", "EVENT_CATG_S",
           "SHORT_DESCRIPT"))

state_pop_dt <- read_csv("USA_States_Data.csv") %>% 
  select(c("STATE_NAME", "POPULATION"))
colnames(state_pop_dt) <- c("STATE", "POPULATION")
data$DATE <- as.Date(data$DATE, format="%m/%d/%Y")
state_pop_dt$STATE <- toupper(state_pop_dt$STATE)
oldData
```

```{r}
data <- inner_join(data, state_pop_dt, by=c("STATE")) 
data$`NEWCD_NORM_500`<- round(data$NEWCONFIRMED/(data$POPULATION/500000))
```

```{r}
bins <- c(-Inf,0,0.25,0.75,1.20,1.55,1.85,2.10,2.35,2.70,3.05,3.40,3.75,
          4.00, 5.00)
data$color_scale <- cut(data$SCORE, breaks=bins)
color_v <- c("#ffffff","#fdfec0", "#fdffa3","#ffd799", "#ffb078","#fc8861",
             "#f2615d","#d8466c","#87377a","#942c81","#721f82",
             "#51127c","#2d1160","#ffd3d1","#100c2E")
names(color_v) = levels(data$color_scale)
```

```{r}
# function that splits event and find specific order
check_event <- function(x, event_order){
  orders = strsplit(x,",")[[1]]
  return(event_order %in% orders)
}

# group event categories into easing/lifting and imposing
group_event_catg <- function(x){
  new_col = c()
  check = substr(x, nchar(x), nchar(x))
  if(check %in% c("M", "R", "A")){
    new_col <- append(new_col, "Mandatory/Re-issued")
  } else if (check %in% c("E", "L")){
    new_col <- append(new_col, "Ease/Lifting")
  } else {
    new_col <- append(new_col, "")
  }
}

data$event_MLER <- sapply(data$EVENT_CATG_S, FUN=group_event_catg)


# category num
catg_num <- function(x){
  new_col = c()
  if (is.na(x)){
    new_col <- append(new_col, x)
  } 
  else if(x=="15M"){
    new_col <- append(new_col, "Face Covering")
  } else if(grepl("2", x)){
    new_col <- append(new_col, "Business Restrictions")
  } else if(grepl("3", x)){
    new_col <- append(new_col, "Indoor Gathering Restrictions")
  } else if(grepl("4", x)){
    new_col <- append(new_col, "Restaurant/Bar Restrictions")
  } else{
    new_col <- append(new_col, "Stay at Home Orders")
  }
}

data$catogory_num <- sapply(data$EVENT_CATG_S, FUN=catg_num)
data$descrip <- paste(data$catogory_num, data$event_MLER)
data$descrip[data$descrip=="NA"] <- NA

```

Event order first time hits. (line)
```{r, warning=FALSE}
#northeast = c("MAINE","MASSACHUSETTS","RHODE ISLAND","CONNECTICUT",
#              "VERMONT","NEW YORK","PENNSYLVANIA",
#             "NEW JERSEY","DELAWARE","MARYLAND")

#southeast = c("WEST VIRGINIA","VIRGINIA","KENTUCKY",
#              "NORTH CAROLINA","ALABAMA")
#states = c("FLORIDA","PENNSYLVANIA", "WISCONSIN","WASHINGTON")

states = c("WEST VIRGINIA","VIRGINIA","KENTUCKY",
              "NORTH CAROLINA","ALABAMA")
event_order = "4E" # can also try 4E

master_df = data.frame(State=character(),
                       Date=as.Date(character()),
                       Events=character(),
                       Newcd_norm=numeric(),
                       Days = numeric(),
                       Events_mler=character(),
                       Score = numeric())
school_opening_df = data.frame()

for (i in (1: length(states))){
  state_data <- data[data$STATE==states[i],]
  fourteen_days <- 14 # graph starts two weeks before 
  may_day <- as.Date("2020-05-01")
  state_data <- state_data[state_data$DATE>=may_day-fourteen_days,]
  state_data <- state_data %>%
    group_by(STATE, DATE) %>%
    summarise(Events = paste(EVENT_CATG_S, collapse = ","),
              Newcd_norm = mean(NEWCD_NORM_500),
              Events_mler = first(event_MLER),
              Score = mean(SCORE),
              Description = paste(descrip, collapse = "\n"))
  
  # turn "NA" into NA
  state_data$Events[state_data$Events=="NA"] <- NA
  # index of order implementation date for the last time issue
  state_mask_ind = which(sapply(state_data$Events, check_event, event_order))

  # if a state never issues mask order then plot all data
  # else the plot starts at the day of mask order
  if(length(state_mask_ind)>0){
    state_data = state_data[(state_mask_ind-fourteen_days):nrow(state_data),]
    # number of days since implementation
    state_data$Days = as.numeric(state_data$DATE-state_data$DATE[1]-fourteen_days)
    # append to final data for plotting
    master_df = rbind(master_df,as.data.frame(state_data))}
}


# add a new column of moving average
# otherwise interactive plot cannot show date
master_df$newcd_norm_moving <- rollmean(master_df$Newcd_norm, 7,
                                fill=NA, align="right")
event_master_df <- master_df[!is.na(master_df$Events) &
                               (master_df$Events!=event_order),] 

    # change Events_mler on September 14th to be School Opening
school_opening_df <- as.data.frame(master_df[master_df$DATE=="2020-09-07",])
school_opening_df$Events_mler <- "Labor Day"




states_trend <- ggplot() +
  geom_vline(xintercept=0) +
  geom_line(data = master_df, aes(x = Days, y = newcd_norm_moving,
                                  color = STATE, Date=DATE, State=STATE, label1=Score),
            size = 1, alpha = 0.5) +
  geom_point(data = event_master_df, aes(x = Days, y = newcd_norm_moving,
                                         shape=Events_mler,
                                         group=Events_mler,
                                         Descript = Description, Date=DATE,
                                         State=STATE, color=STATE),
             alpha = 1, size=3) +
  geom_point(data=school_opening_df, aes(x = Days, y = newcd_norm_moving,
                                         shape = Events_mler),
             size=3) +
  scale_color_discrete(name="")+
  scale_shape_manual(name="", values=c(16,4,17))+
  xlab("Number of Days Since Mask Order ") + 
  ylab("Normalized Daily New Cases") +
  ggtitle( paste("First Time Issue", event_order, " Order Time Series Comparison after May", sep = " ") ) +
  theme_bw()

#states_trend
interactive_p <- ggplotly(states_trend, tooltip=c("State", "Date", "Descript","label1"))

# clean up legend

for (i in 1:length(interactive_p$x$data)){
    if (!is.null(interactive_p$x$data[[i]]$name)){
        interactive_p$x$data[[i]]$name =  gsub("\\(","",str_split(interactive_p$x$data[[i]]$name,",")[[1]][1])
    }
}

interactive_p
```


Event order last time hits. (line)

```{r, warning=FALSE}
#northeast = c("MAINE","MASSACHUSETTS","RHODE ISLAND","CONNECTICUT",
#              "VERMONT","NEW YORK","PENNSYLVANIA",
#             "NEW JERSEY","DELAWARE","MARYLAND")

#southeast = c("WEST VIRGINIA","VIRGINIA","KENTUCKY",
#              "NORTH CAROLINA","ALABAMA")
states = c("FLORIDA","PENNSYLVANIA", "WISCONSIN","WASHINGTON")
event_order = "4E" # can also try 4E

master_df = data.frame(State=character(),
                       Date=as.Date(character()),
                       Events=character(),
                       Newcd_norm=numeric(),
                       Days = numeric(),
                       Events_mler=character(),
                       Score = numeric())
school_opening_df = data.frame()

for (i in (1: length(states))){
  state_data <- data[data$STATE==states[i],]
  fourteen_days <- 14 # graph starts two weeks before 
  may_day <- as.Date("2020-05-01")
  state_data <- state_data[state_data$DATE>=may_day-fourteen_days,]
  state_data <- state_data %>%
    group_by(STATE, DATE) %>%
    summarise(Events = paste(EVENT_CATG_S, collapse = ","),
              Newcd_norm = mean(NEWCD_NORM_500),
              Events_mler = first(event_MLER),
              Score = mean(SCORE),
              Description = paste(descrip, collapse = "\n"))
  
  # turn "NA" into NA
  state_data$Events[state_data$Events=="NA"] <- NA
  # index of order implementation date
  state_mask_ind = which(sapply(state_data$Events, check_event, event_order))[length(state_mask_ind)] 

  # if a state never issues mask order then plot all data
  # else the plot starts at the day of mask order
  if(length(state_mask_ind)>0){
    state_data = state_data[(state_mask_ind-fourteen_days):nrow(state_data),]
    # number of days since implementation
    state_data$Days = as.numeric(state_data$DATE-state_data$DATE[1]-fourteen_days)
    # append to final data for plotting
    master_df = rbind(master_df,as.data.frame(state_data))}
  else{
    master_df = master_df
  }
  
}


# add a new column of moving average
# otherwise interactive plot cannot show date
master_df$newcd_norm_moving <- rollmean(master_df$Newcd_norm, 7,
                                fill=NA, align="right")
event_master_df <- master_df[!is.na(master_df$Events) &
                               (master_df$Events!=event_order),] 

    # change Events_mler on September 14th to be School Opening
school_opening_df <- as.data.frame(master_df[master_df$DATE=="2020-09-07",])
school_opening_df$Events_mler <- "Labor Day"




states_trend <- ggplot() +
  geom_vline(xintercept=0) +
  geom_line(data = master_df, aes(x = Days, y = newcd_norm_moving,
                                  color = STATE, Date=DATE, State=STATE, label1=Score),
            size = 1, alpha = 0.5) +
  geom_point(data = event_master_df, aes(x = Days, y = newcd_norm_moving,
                                         shape=Events_mler,
                                         group=Events_mler,
                                         Descript = Description, Date=DATE,
                                         State=STATE, color=STATE),
             alpha = 1, size=3) +
  geom_point(data=school_opening_df, aes(x = Days, y = newcd_norm_moving,
                                         shape = Events_mler),
             size=3) +
  scale_color_discrete(name="")+
  scale_shape_manual(name="", values=c(16,4,17))+
  xlab("Number of Days Since Mask Order ") + 
  ylab("Normalized Daily New Cases") +
  ggtitle( paste("First Time Issue", event_order, " Order Time Series Comparison after May", sep = " ") ) +
  theme_bw()

#states_trend
interactive_p <- ggplotly(states_trend, tooltip=c("State", "Date", "Descript","label1"))

# clean up legend

for (i in 1:length(interactive_p$x$data)){
    if (!is.null(interactive_p$x$data[[i]]$name)){
        interactive_p$x$data[[i]]$name =  gsub("\\(","",str_split(interactive_p$x$data[[i]]$name,",")[[1]][1])
    }
}

interactive_p
```



First time issue the order by points
```{r, warning=FALSE}
#northeast = c("MAINE","MASSACHUSETTS","RHODE ISLAND","CONNECTICUT",
#              "VERMONT","NEW YORK","PENNSYLVANIA",
#             "NEW JERSEY","DELAWARE","MARYLAND")

#southeast = c("WEST VIRGINIA","VIRGINIA","KENTUCKY",
#              "NORTH CAROLINA","ALABAMA")
#states = c("FLORIDA","PENNSYLVANIA", "WISCONSIN","WASHINGTON")
states = c("FLORIDA","PENNSYLVANIA", "WISCONSIN","WASHINGTON")
#states = c("FLORIDA")
event_order = "4E" # can also try 4E

master_df = data.frame(State=character(),
                       Date=as.Date(character()),
                       Events=character(),
                       Newcd_norm=numeric(),
                       Days = numeric(),
                       Events_mler=character(),
                       Score = numeric())
school_opening_df = data.frame()





for (i in (1: length(states))){
  state_data <- data[data$STATE==states[i],]
  fourteen_days <- 14 # graph starts two weeks before 
  may_day <- as.Date("2020-05-01")
  state_data <- state_data[state_data$DATE>=may_day-fourteen_days,]
  state_data <- state_data %>%
    group_by(STATE, DATE) %>%
    summarise(Events = paste(EVENT_CATG_S, collapse = ","),
              Newcd_norm = mean(NEWCD_NORM_500),
              Events_mler = first(event_MLER),
              Score = mean(SCORE),
              Description = paste(descrip, collapse = "\n"),
              color_scale = first(color_scale))
  
  # turn "NA" into NA
  state_data$Events[state_data$Events=="NA"] <- NA
  # index of order implementation date for the last time issue
  state_mask_ind = which(sapply(state_data$Events, check_event, event_order))

  # if a state never issues mask order then plot all data
  # else the plot starts at the day of mask order
  if(length(state_mask_ind)>0){
    state_data = state_data[(state_mask_ind-fourteen_days):nrow(state_data),]
    # number of days since implementation
    state_data$Days = as.numeric(state_data$DATE-state_data$DATE[1]-fourteen_days)
    # append to final data for plotting
    master_df = rbind(master_df,as.data.frame(state_data))}
  
}


# add a new column of moving average
# otherwise interactive plot cannot show date
master_df$newcd_norm_moving <- rollmean(master_df$Newcd_norm, 7,
                                fill=NA, align="right")
event_master_df <- master_df[!is.na(master_df$Events) &
                               (master_df$Events!=event_order),] 

    # change Events_mler on September 14th to be School Opening
school_opening_df <- as.data.frame(master_df[master_df$DATE=="2020-09-07",])
school_opening_df$Events_mler <- "Labor Day"





states_trend <- ggplot() +
  geom_vline(xintercept=0) +
  geom_vline(xintercept=20)+
  geom_point(data=master_df, aes(x=Days, y=newcd_norm_moving,
                                 fill=color_scale, label1=Score,
                                 label2=STATE),
             shape=21, size=2.5, color="transparent")+
  scale_fill_manual(values=color_v, name="")+
  geom_point(data = event_master_df, aes(x = Days, 
                                         y = newcd_norm_moving,
                                         shape=Events_mler,
                                         group=Events_mler,
                                         Descript = Description, 
                                         Date=DATE,
                                         State=STATE),
             alpha = 1, size=3) +
  geom_point(data=school_opening_df, aes(x = Days, y = newcd_norm_moving,
                                         shape = Events_mler),
             size=3) +
  scale_color_discrete(name="")+
  scale_shape_manual(name="", values=c(16,4,17))+
  xlab("Number of Days Since Mask Order ") + 
  ylab("Normalized Daily New Cases") +
  ggtitle( paste("First Time Issue", event_order, " Order Time Series Comparison after May", sep = " ") ) +
  theme_bw()

#states_trend
interactive_p <- ggplotly(states_trend, tooltip=c("State", "Date", "Descript","label1","label2"))
# clean up legend

for (i in 1:length(interactive_p$x$data)){
    if (!is.null(interactive_p$x$data[[i]]$name)){
        interactive_p$x$data[[i]]$name =  gsub("\\(","",str_split(interactive_p$x$data[[i]]$name,",")[[1]][1])
    }
}

interactive_p
```



Last time issue the order by points

```{r, warning=FALSE}
#northeast = c("MAINE","MASSACHUSETTS","RHODE ISLAND","CONNECTICUT",
#              "VERMONT","NEW YORK","PENNSYLVANIA",
#             "NEW JERSEY","DELAWARE","MARYLAND")

#southeast = c("WEST VIRGINIA","VIRGINIA","KENTUCKY",
#              "NORTH CAROLINA","ALABAMA")
#states = c("FLORIDA","PENNSYLVANIA", "WISCONSIN","WASHINGTON")
states = c("FLORIDA","PENNSYLVANIA", "WISCONSIN","WASHINGTON")
#states = c("FLORIDA")
event_order = "4E" # can also try 4E

master_df = data.frame(State=character(),
                       Date=as.Date(character()),
                       Events=character(),
                       Newcd_norm=numeric(),
                       Days = numeric(),
                       Events_mler=character(),
                       Score = numeric())
school_opening_df = data.frame()





for (i in (1: length(states))){
  state_data <- data[data$STATE==states[i],]
  fourteen_days <- 14 # graph starts two weeks before 
  may_day <- as.Date("2020-05-01")
  state_data <- state_data[state_data$DATE>=may_day-fourteen_days,]
  state_data <- state_data %>%
    group_by(STATE, DATE) %>%
    summarise(Events = paste(EVENT_CATG_S, collapse = ","),
              Newcd_norm = mean(NEWCD_NORM_500),
              Events_mler = first(event_MLER),
              Score = mean(SCORE),
              Description = paste(descrip, collapse = "\n"),
              color_scale = first(color_scale))
  
  # turn "NA" into NA
  state_data$Events[state_data$Events=="NA"] <- NA
  # index of order implementation date for the last time issue
  state_mask_ind = which(sapply(state_data$Events, check_event, event_order))[length(state_mask_ind)] 

  # if a state never issues mask order then plot all data
  # else the plot starts at the day of mask order
  if(length(state_mask_ind)>0){
    state_data = state_data[(state_mask_ind-fourteen_days):nrow(state_data),]
    # number of days since implementation
    state_data$Days = as.numeric(state_data$DATE-state_data$DATE[1]-fourteen_days)
    # append to final data for plotting
    master_df = rbind(master_df,as.data.frame(state_data))}
  
}


# add a new column of moving average
# otherwise interactive plot cannot show date
master_df$newcd_norm_moving <- rollmean(master_df$Newcd_norm, 7,
                                fill=NA, align="right")
event_master_df <- master_df[!is.na(master_df$Events) &
                               (master_df$Events!=event_order),] 

    # change Events_mler on September 14th to be School Opening
school_opening_df <- as.data.frame(master_df[master_df$DATE=="2020-09-07",])
school_opening_df$Events_mler <- "Labor Day"





states_trend <- ggplot() +
  geom_vline(xintercept=0) +
  geom_vline(xintercept=20)+
  geom_point(data=master_df, aes(x=Days, y=newcd_norm_moving,
                                 fill=color_scale, label1=Score,
                                 label2=STATE),
             shape=21, size=2.5, color="transparent")+
  scale_fill_manual(values=color_v, name="")+
  geom_point(data = event_master_df, aes(x = Days, 
                                         y = newcd_norm_moving,
                                         shape=Events_mler,
                                         group=Events_mler,
                                         Descript = Description, 
                                         Date=DATE,
                                         State=STATE),
             alpha = 1, size=3) +
  geom_point(data=school_opening_df, aes(x = Days, y = newcd_norm_moving,
                                         shape = Events_mler),
             size=3) +
  scale_color_discrete(name="")+
  scale_shape_manual(name="", values=c(16,4,17))+
  xlab("Number of Days Since Mask Order ") + 
  ylab("Normalized Daily New Cases") +
  ggtitle( paste("First Time Issue", event_order, " Order Time Series Comparison after May", sep = " ") ) +
  theme_bw()

#states_trend
interactive_p <- ggplotly(states_trend, tooltip=c("State", "Date", "Descript","label1","label2"))
# clean up legend

for (i in 1:length(interactive_p$x$data)){
    if (!is.null(interactive_p$x$data[[i]]$name)){
        interactive_p$x$data[[i]]$name =  gsub("\\(","",str_split(interactive_p$x$data[[i]]$name,",")[[1]][1])
    }
}

interactive_p
```