---
title: "Undergrad research"
authors: "Alvin Pan"
Andrew IDs: "qpan"
output:
  pdf_document:
    toc: no
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
---
```{r}
library("readxl")
library(tidyverse)
```



```{r}
covid = data.frame(read_excel("COVID_CASES_IA_KS_20201111wPop_public.xlsx"))
covid.g1 = data.frame(read_excel("precoord_COVID_IA_CNTY_20201113_Upd1116.xlsx"))
```

```{r}
head(covid)
```

```{r}
head(covid.g1)
```


unify date syntax
```{r}
covid$DATE = as.Date(covid$DATE, "%m/%d/%y")
covid.g1$DATE = as.Date(covid.g1$DATE, "%m-%d-%y")
```



```{r}
#function to union 2 feature vectors
combine.attributes <- function(x, y) {
  n = length(x)
  for (i in 1:n) {
    if (is.na(x[i])) {
      x[i] = y[i]
    }
  }
  return (x)
}
```


```{r}
#function to union duplicate features
clean.combined.data <- function(data, attrs) {
  for (name in attrs) {
    data[, name] = combine.attributes(covid.com[, paste(name, ".x", sep="")], covid.com[, paste(name, ".y", sep="")])
    data[, paste(name, ".x", sep="")] = NULL
    data[, paste(name, ".y", sep="")] = NULL
  }
  return (dplyr::arrange(data, COUNTY, STATE, DATE))
}
```




```{r}
#function to fill the NAs with the most recently observed non-NA for all input features of data frame
extend.attr <- function(data, features) {
  n = dim(data)[1]
  for (feature in features) {
    xs = rep(0, n)
    prev.state = NULL
    curr.x = 0
    for (i in 1:n) {
      curr.state = data$STATE[i]
      if (!(is.na(data[,feature][i]))) {
        curr.x = data[, feature][i]
      } else {
        if (is.null(prev.state) || (curr.state != prev.state)) {
          curr.x = 0
          prev.state = curr.state
        }
      }
      xs[i] = curr.x
    }  
    data[, feature] = xs
  }
  return (data)
}
```




```{r}
# extract top n states with the most people
top_pop_states <- function(data, n=5) {
  d = data %>% group_by(STATE) %>% summarize(POPULATION = mean(POPULATION, na.rm = TRUE))
  return (top_n(d, n=n, wt=POPULATION)[[1]])                          
}
```


```{r}
duplicated.attributes = c("STUSAB")
```

combine 2 data frames
```{r}
covid.com = covid %>% full_join(covid.g1, by = c("COUNTY", "STATE", "DATE"))
head(covid.com)
```



Sort data by state and then date
```{r}
covid.com = clean.combined.data(covid.com, duplicated.attributes)
```

```{r}
head(covid.com)
```

```{r}
covid.com = extend.attr(covid.com, c("SCORE"))
```






```{r}
which(!is.na(covid.com$EVENT_CATG))
tail(covid.com[covid.com$COUNTY == "HENRY",c('DATE', 'SCORE')], 160)
```



```{r}
write.csv(covid.com, "covid.com.csv")
```

