---
title: "Undergrad research"
authors: "Alvin Pan"
Andrew IDs: "qpan"
output:
  pdf_document:
    toc: no
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
---
```{r}
library("readxl")
library(tidyverse)
library(np)
library(GauPro)
library("GPfit")
library("lhs")
```



```{r}
covid = data.frame(read_excel("../data/COVID_CASES.xlsx"))
covid.g1 = data.frame(read_excel("../data/COVID_ALL_G1.xlsx"))
```

```{r}
head(covid)
```

```{r}
head(covid.g1)
```


unify date syntax
```{r}
covid$DATE = as.Date(covid$DATE)
```



```{r}
covid.g1$DATE = as.Date(parse_date_time(covid.g1$DATE, orders="mdy"))
```


```{r}
#function to union 2 feature vectors
combine.attributes <- function(x, y) {
  n = length(x)
  for (i in 1:n) {
    if (is.na(x[i])) {
      x[i] = y[i]
    }
  }
  return (x)
}
```


```{r}
#function to union duplicate features
clean.combined.data <- function(data, attrs) {
  for (name in attrs) {
    data[, name] = combine.attributes(covid.com[, paste(name, ".x", sep="")], covid.com[, paste(name, ".y", sep="")])
    data[, paste(name, ".x", sep="")] = NULL
    data[, paste(name, ".y", sep="")] = NULL
  }
  return (dplyr::arrange(data, STATE, DATE))
}
```




```{r}
#function to fill the NAs with the most recently observed non-NA for all input features of data frame
extend.attr <- function(data, features) {
  n = dim(data)[1]
  for (feature in features) {
    xs = rep(0, n)
    prev.state = NULL
    curr.x = 0
    for (i in 1:n) {
      curr.state = data$STATE[i]
      if (!(is.na(data[,feature][i]))) {
        curr.x = data[, feature][i]
      } else {
        if (is.null(prev.state) || (curr.state != prev.state)) {
          curr.x = 0
          prev.state = curr.state
        }
      }
      xs[i] = curr.x
    }  
    data[, feature] = xs
  }
  return (data)
}
```

```{r}
# extract top n states with the most people
top_pop_states <- function(data, n=5) {
  d = data %>% group_by(STATE) %>% summarize(POPULATION = mean(POPULATION, na.rm = TRUE))
  return (top_n(d, n=n, wt=POPULATION)[[1]])                          
}
```


```{r}
# plot covid cases for top population states
plot_states <- function(data, states, feature, x=2, y=3) {
  # top_states = top_pop_states(covid, n)
  par(mfrow=c(x,y), mar=c(4,4,2,0.5)) # Setup grid, margins
  for (state in states) {
    d = data %>% filter(STATE == state)
    plot(d$DATE, d[,feature], xlab = "Time", ylab = feature, main = paste("COVID cases in", state), pch = 20, cex = 0.5)
  }
}
```



```{r}
plot_smooth_func <- function(data, states, feature, method="spline", x=1, y=3, df=20, bws=10) {
  # top_states = top_pop_states(covid, n)
  par(mfrow=c(x,y), mar=c(4,4,2,0.5)) # Setup grid, margins
  data = subset(data, !is.na(DATE) & !is.na(data[, feature]))
  if (method == "spline") {
    for (state in states) {
      d = data %>% filter(STATE == state)
      dates = as.numeric(d$DATE)
      plot(d$DATE, d[,feature], xlab = "Time", ylab = feature, main = paste("COVID cases in", state), pch = 20, cex = 0.5)
      sm = smooth.spline(d[,feature]~dates, df=df)
      sm.pred = predict(sm, dates)$y
      lines(d$DATE, sm.pred, pch = 20, cex = 0.5, col = 3)
    }
  } else if (method == "gp") {
    for (state in states) {
      d = data %>% filter(STATE == state)
      dates = as.numeric(d$DATE)
      dates = (dates-min(dates))/(max(dates)-min(dates))
      #kern <- Matern52$new(0)
      #trend.0 <- trend_0$new()
      #gpk.exp <- GauPro_kernel_model$new(matrix(dates, ncol=1), d[,feature], kernel=kern, parallel=FALSE)
      #if (requireNamespace("MASS", quietly = TRUE)) {
      #  plot(gpk.exp)
      #  axis(1, at=dates, labels=d$DATE)
      #}
      n = length(dates)
      x <- matrix(dates, nrow=n)
      y <- matrix(as.vector(d[,feature]), nrow=n)
      
      GPmodel <- GP_fit(x, y)
    }
  } else { #kernel regression
    for (state in states) {
      d = data %>% filter(STATE == state)
      dates = as.numeric(d$DATE)
      plot(d$DATE, d[,feature], xlab = "Time", ylab = feature, main = paste("COVID cases in", state), pch = 20, cex = 0.5)
      gm = npreg(dates, d[,feature], bws = bws)
      gm.pred = predict(gm, newdata=dates)
      lines(d$DATE, gm.pred, pch = 20, cex = 0.5, col = 5)
    }
  }
}
```


```{r}
duplicated.attributes = c("STUSAB", "LATITUDE", "LONGITUDE", "STATEFP")
```

combine 2 data frames
```{r}
covid.com = covid %>% full_join(covid.g1, by = c("STATE", "DATE"))
```



Sort data by state and then date
```{r}
covid.com = clean.combined.data(covid.com, duplicated.attributes)
```

```{r}
head(covid.com)
```

```{r}
covid.com = extend.attr(covid.com, c("SCORE"))
```

```{r}
states = top_pop_states(covid)
plot_states(covid.com, states, 'SCORE')
```

```{r}
plot_smooth_func(covid.com, c("PENNSYLVANIA", "WASHINGTON", "CALIFORNIA"), 'NEWCD_NORM_500', method="spline",x=1,y=2,df=20,bws=7)
```


```{r}
plot_smooth_func(covid.com, c("PENNSYLVANIA", "WASHINGTON", "CALIFORNIA"), 'NEWCD_NORM_500', method="kernel",x=1,y=2,df=20,bws=7)
```

```{r}
plot_smooth_func(covid.com, c("PENNSYLVANIA", "WASHINGTON", "CALIFORNIA"), 'NEWCD_NORM_500', method="gp",x=1,y=2,df=20,bws=7)
```

---------below are just random experiments


```{r}
plot(covid.com$DATE, covid.com$SCORE)
```


```{r}
cont.cols = c(5:11,14:17)
```



```{r}
par(mfrow=c(3,4), mar=c(4,4,2,0.5)) # Setup grid, margins
for (j in cont.cols) {
  hist(covid[,j], xlab=colnames(covid)[j],
       main=paste("Hist of", colnames(covid)[j]),
       col="lightblue", breaks=20)
}
```


```{r}
grouped.df = covid %>% group_by(STATE) %>% summarize(POPULATION = sum(sqrt(POPULATION), na.rm = TRUE), NEWCONFIRMED = sum(log(NEWCONFIRMED+1), na.rm = TRUE), CUMCONFIRMED = sum(log(CUMCONFIRMED+1), na.rm = TRUE), NEWDEATHS=sum(log(NEWDEATHS+1), na.rm = TRUE), CUMDEATHS=sum(log(CUMDEATHS+1), na.rm = TRUE)) %>% data.frame()
```

```{r}
grouped.df
```


```{r}
par(mfrow=c(2,3), mar=c(4,4,2,0.5)) # Setup grid, margins
for (j in (2:6)) {
  hist(grouped.df[,j], xlab=colnames(grouped.df)[j],
       main=paste("Hist of", colnames(grouped.df)[j]),
       col="lightblue", breaks=20)
}
```



```{r}
head(covid.com)
```


```{r}
states = top_pop_states(covid)
plot_states(covid.com, states, 'SCORE')
```

```{r}
matrix(rexp(n), nrow=n)
```


```{r}
library("GPfit")
library("lhs")
n <- 7
x <- matrix(1:n/7, nrow=n)
y <- matrix(rnorm(n), nrow=n)

GPmodel <- GP_fit(x, y)

plot(GPmodel)
```


```{r}
plot_states(covid, 'NEWCONFIRMED')
```


```{r}
write.csv(covid.com, "../data/covid.com.csv")
```

