

```{r, message=FALSE, warning=FALSE, echo = FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(readr)
library(ggfortify)
library(ggseas)
library(plotly)
library(zoo)
```

## States Mask Order
```{r}
data <- read_csv("State_Cases_G1_Merged_01112021.csv") %>% 
  select(c("STATE","DATE","NEWCONFIRMED", "SCORE", "EVENT_CATG_S",
           "SHORT_DESCRIPT"))

state_pop_dt <- read_csv("USA_States_Data.csv") %>% 
  select(c("STATE_NAME", "POPULATION"))
colnames(state_pop_dt) <- c("STATE", "POPULATION")
data$DATE <- as.Date(data$DATE, format="%m/%d/%Y")
state_pop_dt$STATE <- toupper(state_pop_dt$STATE)
```
```{r}
data <- inner_join(data, state_pop_dt, by=c("STATE")) 
data$`New Cases/500,000 ppl`<-
  round(data$NEWCONFIRMED/(data$POPULATION/500000))
```

```{r}
# function that splits event and find specific order
check_event <- function(x, event_order){
  orders = strsplit(x,",")[[1]]
  return(event_order %in% orders)
}

# group event categories into easing/lifting and imposing
group_event_catg <- function(x){
  new_col = c()
  check = substr(x, nchar(x), nchar(x))
  if(check %in% c("M", "R", "A")){
    new_col <- append(new_col, "Mandatory/Re-issued")
  } else if (check %in% c("E", "L")){
    new_col <- append(new_col, "Ease/Lifting")
  } else {
    new_col <- append(new_col, "")
  }
}

data$event_MLER <- sapply(data$EVENT_CATG_S, FUN=group_event_catg)


# category num
catg_num <- function(x){
  new_col = c()
  if (is.na(x)){
    new_col <- append(new_col, x)
  }
  else if(x=="15M"){
    new_col <- append(new_col, "Face Covering")
  } else if(grepl("2", x)){
    new_col <- append(new_col, "Business Restrictions")
  } else if(grepl("3", x)){
    new_col <- append(new_col, "Indoor Gathering Restrictions")
  } else if(grepl("4", x)){
    new_col <- append(new_col, "Restaurant/Bar Restrictions")
  } else{
    new_col <- append(new_col, "Stay at Home Orders")
  }
}

data$catogory_num <- sapply(data$EVENT_CATG_S, FUN=catg_num)
data$descrip <- paste(data$catogory_num, data$event_MLER)
data$descrip[data$descrip=="NA"] <- NA


```


```{r, warning=FALSE}
# northeast = c("MAINE","MASSACHUSETTS","RHODE ISLAND","CONNECTICUT",
#               "VERMONT","NEW YORK","PENNSYLVANIA",
#               "NEW JERSEY","DELAWARE","MARYLAND")
# southeast = c("WEST VIRGINIA","VIRGINIA","KENTUCKY",
#               "NORTH CAROLINA","ALABAMA")

states = c("FLORIDA", "DISTRICT OF COLUMBIA", "NEW JERSEY")

#event_order = "4E" # can also try 4E

master_df = data.frame(State=character(),
                       Date=as.Date(character()),
                       Events=character(),
                       Newcd_norm=numeric(),
                       Days = numeric(),
                       Events_mler=character(),
                       Score = numeric())
school_opening_df = data.frame()

for (i in (1: length(states))){
  state_data <- data[data$STATE==states[i],]
  fourteen_days <- 14 # graph starts two weeks before 
  seven_days <- 7
  may_day <- as.Date("2020-05-01")
  state_data <- state_data[state_data$DATE>=may_day-fourteen_days-7,]
  # aggregate by state, date and combine events & values
  state_data <- state_data %>%
    group_by(STATE, DATE) %>%
    summarise(Events = paste(EVENT_CATG_S, collapse = ","),
              Newcd_norm = mean(`New Cases/500,000 ppl`),
              Events_mler = first(event_MLER),
              Score = mean(SCORE),
              Description = paste(descrip, collapse = "\n"))
  # turn "NA" into NA
  state_data$Events[state_data$Events=="NA"] <- NA
  # index of order implementation date
  #state_mask_ind = which(sapply(state_data$Events, check_event, event_order)) 
  first_hit_3 <- which(state_data$Score>=3 & state_data$DATE>=may_day)[1]


  # if a state never issues mask order then plot all data
  # else the plot starts at the day of mask order
  if(length(first_hit_3)>0){
    state_data <- 
      state_data[(first_hit_3-fourteen_days):nrow(state_data),]
    # number of days since implementation
    state_data$Days = as.numeric(state_data$DATE-state_data$DATE[1]-fourteen_days)
    # append to final data for plotting
    master_df <- rbind(master_df, as.data.frame(state_data))}
}


# add a new column of moving average
# otherwise interactive plot cannot show date
master_df$newcd_norm_moving <- rollmean(master_df$Newcd_norm, 7,
                                fill=NA, align="right")
event_master_df <- master_df[!is.na(master_df$Events),]
                               #(master_df$Events!=event_order),] 

# change Events_mler on September 14th to be School Opening
school_opening_df <- as.data.frame(master_df[master_df$DATE=="2020-09-07",])
school_opening_df$Events_mler <- "Labor Day"


states_trend <- ggplot() +
  geom_vline(xintercept=0) +
  geom_line(data = master_df, aes(x = Days, y = newcd_norm_moving,
                                  color = STATE, Date=DATE, State=STATE),
            size = 1, alpha = 0.5) +
  geom_point(data = event_master_df, aes(x = Days, y = newcd_norm_moving,
                                         shape=Events_mler,
                                         group=Events_mler,
                                         Date=DATE,
                                         State=STATE, color=STATE,
                                         Descript = Description),
             alpha = 1, size=3) +
  geom_point(data=school_opening_df, aes(x = Days, y = newcd_norm_moving,
                                         shape = Events_mler),
             size=3) +
  scale_color_discrete(name="")+
  scale_shape_manual(name="", values=c(16,4,17))+
  xlab("Number of Days Since Mask Order") + 
  ylab("Normalized Daily New Cases") +
  ggtitle("First Time Score>=3 Series Comparison after May") +
  theme_bw()

#states_trend
interactive_p <- ggplotly(states_trend, tooltip=c("State", "Date", "Descript"))

# clean up legend

for (i in 1:length(interactive_p$x$data)){
    if (!is.null(interactive_p$x$data[[i]]$name)){
        interactive_p$x$data[[i]]$name =  gsub("\\(","",str_split(interactive_p$x$data[[i]]$name,",")[[1]][1])
    }
}

interactive_p
```



mostly duplicate for last time hit 3 
```{r, warning=FALSE}
# northeast = c("MAINE","MASSACHUSETTS","RHODE ISLAND","CONNECTICUT",
#               "VERMONT","NEW YORK","PENNSYLVANIA",
#               "NEW JERSEY","DELAWARE","MARYLAND")
# southeast = c("WEST VIRGINIA","VIRGINIA","KENTUCKY",
#               "NORTH CAROLINA","ALABAMA")

states = c("FLORIDA", "LOUISIANA", "COLORADO", "KANSAS")

#event_order = "4E" # can also try 4E

master_df = data.frame(State=character(),
                       Date=as.Date(character()),
                       Events=character(),
                       Newcd_norm=numeric(),
                       Days = numeric(),
                       Events_mler=character(),
                       Score = numeric())
school_opening_df = data.frame()

for (i in (1: length(states))){
  state_data <- data[data$STATE==states[i],]
  fourteen_days <- 14 # graph starts two weeks before 
  may_day <- as.Date("2020-05-01")
  state_data <- state_data[state_data$DATE>=may_day-fourteen_days,]
  # aggregate by state, date and combine events & values
  state_data <- state_data %>%
    group_by(STATE, DATE) %>%
    summarise(Events = paste(EVENT_CATG_S, collapse = ","),
              Newcd_norm = mean(`New Cases/500,000 ppl`),
              Events_mler = first(event_MLER),
              Score = mean(SCORE),
              Description = paste(descrip, collapse = "\n"))
  # turn "NA" into NA
  state_data$Events[state_data$Events=="NA"] <- NA
  # index of order implementation date
  #state_mask_ind = which(sapply(state_data$Events, check_event, event_order)) 
  first_hit_3 <- which(state_data$Score>=3 & state_data$DATE>=may_day)[1]
  last_hit_3 <- first_hit_3 # initiate index of last time hit 3
  for (i in first_hit_3:nrow(state_data)){
    if (state_data[i,"Score"]>=3){
      last_hit_3 <- i
    }
  }


  # if a state never issues mask order then plot all data
  # else the plot starts at the day of mask order
  if(length(first_hit_3)>0){
    state_data <- state_data[(last_hit_3-fourteen_days):nrow(state_data),]
    # number of days since implementation
    state_data$Days = as.numeric(state_data$DATE-state_data$DATE[1]-fourteen_days)
    # append to final data for plotting
    master_df <- rbind(master_df, as.data.frame(state_data))}
}


# add a new column of moving average
# otherwise interactive plot cannot show date
master_df$newcd_norm_moving <- rollmean(master_df$Newcd_norm, 7,
                                fill=NA, align="right")
event_master_df <- master_df[!is.na(master_df$Events),]
                               #(master_df$Events!=event_order),] 

# change Events_mler on September 14th to be School Opening
school_opening_df <- as.data.frame(master_df[master_df$DATE=="2020-09-07",])
school_opening_df$Events_mler <- "Labor Day"


states_trend <- ggplot() +
  geom_vline(xintercept=0) +
  geom_line(data = master_df, aes(x = Days, y = newcd_norm_moving,
                                  color = STATE, Date=DATE, State=STATE),
            size = 1, alpha = 0.5) +
  geom_point(data = event_master_df, aes(x = Days, y = newcd_norm_moving,
                                         shape=Events_mler,
                                         group=Events_mler,
                                         Date=DATE,
                                         State=STATE, color=STATE,
                                         Descript = Description),
             alpha = 1, size=3) +
  geom_point(data=school_opening_df, aes(x = Days, y = newcd_norm_moving,
                                         shape = Events_mler),
             size=3) +
  scale_color_discrete(name="")+
  scale_shape_manual(name="", values=c(16,4,17))+
  xlab("Number of Days Since Mask Order") + 
  ylab("Normalized Daily New Cases") +
  ggtitle("Last Time Score>=3 Series Comparison after May") +
  theme_bw()

#states_trend
interactive_p <- ggplotly(states_trend, tooltip=c("State", "Date", "Descript"))

# clean up legend

for (i in 1:length(interactive_p$x$data)){
    if (!is.null(interactive_p$x$data[[i]]$name)){
        interactive_p$x$data[[i]]$name =  gsub("\\(","",str_split(interactive_p$x$data[[i]]$name,",")[[1]][1])
    }
}

interactive_p
```


