1. import libraries and and dataset
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(readr)
library(plotly)
library(ggfortify)
library(ggseas)
library(chron)
data <- read_csv("covid.com.csv") %>% 
  select(c(-1))
```

2. preprocess data
```{r}


# group event categories into easing/lifting and imposing
group_event_catg <- function(x){
  new_col = c()
  check = substr(x, nchar(x), nchar(x))
  if(check %in% c("M", "R")){
    new_col <- append(new_col, "Mandatory/Recommended")
  } else if (check %in% c("E", "L")){
    new_col <- append(new_col, "Ease/Lifting")
  } else {
    new_col <- append(new_col, x)
  }
}
#state_data$big_event_catg <- sapply(state_data$EVENT_CATG_S,
                                    #FUN=group_event_catg)

# text color bins
bins <- c(-Inf,0,0.25,0.75,1.20,1.55,1.85,2.10,2.35,2.70,3.05,3.40,3.75,
          4.00, 5.00)
data$color_scale <- cut(data$SCORE, breaks=bins)
color_v <- c("#ffffff","#fdfec0","#ffd799","#ffb078","#fc8861","#f2615d",
             "#d8466c","#87377a","#942c81","#721f82","#51127c", "#2d1160",
             "#ffd3d1", "#100c2e")

color_event_v <- c("#ff0000","#e08c75","#f2cec4","#f2cf05","#ede02b",
                      "#ada63e","#b3b827","#144d6b", "#07a3f5",
                      "#81b7d4", "#a3bcc9","#cfeeff", "#9905f5","#c99fe3",
                      "#480c6e", "#715b80", "#d324f2", "#ffffff")
names(color_event_v) = levels(as.factor(data$EVENT_CATG_S))
names(color_v) = levels(data$color_scale)

data$is_weekend <- is.weekend(chron(as.numeric(data$DATE)))

```


3. plot lag graphs
```{r, message=FALSE, warning=FALSE}
# # 1 day lag
# ggplot(data=state_data)+
#   geom_point(aes(x=NEWCD_NORM_500, y=lead(NEWCD_NORM_500),
#                  col=as.factor(big_event_catg)))+
#   labs(title=paste(str_to_title(state),"lag 1"), 
#        x="Today's Norm New Confirmed Cases",
#        y="Tomorrow's Norm NC Cases",
#        col = "Event_Category")+
#   theme_bw()
# 
# # 3 day lag
# ggplot(data=state_data)+
#   geom_point(aes(x=NEWCD_NORM_500, y=lead(NEWCD_NORM_500, n=3),
#                  col=as.factor(big_event_catg)))+
#   labs(title=paste(str_to_title(state),"lag 3"), 
#        x="Today's Norm New Confirmed Cases",
#        y="Norm NC Cases 3 days later",
#        col = "Event_Category")+
#   theme_bw()
# 
# # 5 day lag
# ggplot(data=state_data)+
#   geom_point(aes(x=NEWCD_NORM_500, y=lead(NEWCD_NORM_500, n=5),
#                  col=as.factor(big_event_catg)))+
#   labs(title=paste(str_to_title(state),"lag 5"), 
#        x="Today's Norm New Confirmed Cases",
#        y="Norm NC Cases 5 days later",
#        col = "Event_Category")+
#   theme_bw()
# 
# # 7 day lag
# ggplot(data=state_data)+
#   geom_point(aes(x=NEWCD_NORM_500, y=lead(NEWCD_NORM_500, n=7),
#                  col=as.factor(big_event_catg)))+
#   labs(title=paste(str_to_title(state),"lag 7"), 
#        x="Today's Norm New Confirmed Cases",
#        y="Norm NC Cases 7 days later",
#        col = "Event_Category")+
#   theme_bw()
# 
# # 10 day lag
# ggplot(data=state_data)+
#   geom_point(aes(x=NEWCD_NORM_500, y=lead(NEWCD_NORM_500, n=10),
#                  col=as.factor(big_event_catg)))+
#   labs(title=paste(str_to_title(state),"lag 10"), 
#        x="Today's Norm New Confirmed Cases",
#        y="Norm NC Cases 10 days later",
#        col = "Event_Category")+
#   theme_bw()
#   
```


4. put into function
```{r}
plot_lag <- function(state, lead_n){
  state_data <- data[data$STATE==state,]
  identity_x <- seq(0, max(na.omit(state_data$NEWCD_NORM_500)), by=1)
  identity_y <- identity_x
  state_data$big_event_catg <- sapply(state_data$EVENT_CATG_S,
                                    FUN=group_event_catg)
  
  corr <- round(acf(na.omit(state_data$NEWCD_NORM_500),
                               lag.max=lead_n, 
              plot=FALSE)[lead_n]$acf[1], digits=2)
  
  plot <- ggplot(data=state_data)+
    geom_point(aes(x=NEWCD_NORM_500, y=lead(NEWCD_NORM_500, n=lead_n),
                   col=as.factor(big_event_catg),
                   alpha=as.factor(big_event_catg)), size=2)+
    scale_color_manual(values=c("red","blue","white"),name="Event Category",
                        labels=c("Ease/Lifting", "Mandatory/Re-issued"))+
    scale_alpha_manual(values=c(1,1,0))+
    geom_line(data=data.frame(identity_x, identity_y),
              aes(x=identity_x, y=identity_y), linetype="dotted", size=1)+
    labs(title=paste(str_to_title(state),"lag", lead_n, "correlation=", corr), 
         x="Today's Norm New Confirmed Cases",
         y=paste("Normalized New Daily Cases", lead_n, "days later"),
         col = "Event_Category")+
    theme_bw()
  
  print(plot)
}
```



5. create an interactive version function for lag
```{r}
plot_lag_interact <- function(state, lead_n){
  state_data <- data[data$STATE==state,]
  state_data$big_event_catg <- sapply(state_data$EVENT_CATG_S,
                                    FUN=group_event_catg)

  identity_x <- seq(0, max(na.omit(state_data$NEWCD_NORM_500)), by=1)
  identity_y <- identity_x
  
  
  plot2 <- ggplot(data=state_data)+
    geom_point(aes(x=NEWCD_NORM_500, y=lead(NEWCD_NORM_500, n=lead_n),
                   col=as.factor(big_event_catg),
                   Date=DATE, Event=EVENT_CATG_S, alpha=0.9,
                   shape=as.factor(is_weekend)))+
     geom_line(data=data.frame(identity_x, identity_y),
              aes(x=identity_x, y=identity_y), linetype="dotted", size=1)+
    labs(title=paste(str_to_title(state),"lag", lead_n, "correlation=", corr), 
         x="Today's Norm New Confirmed Cases",
         y=paste("Norm NC Cases", lead_n, "days later"),
         col = "Event_Category")+
    theme_bw()
  
  ggplotly(plot2, tooltip=c("x", "y", "Date", "Event"))
}
```



**7. run plot functions in specified state and lag days
```{r, message=FALSE, warning=FALSE}
state = "WISCONSIN"
for (day in c(14, 21, 30, 45, 60, 90)){
  plot_lag(state, day)
}
```



**8. run interactive lag plot functions with specified state and lag days
```{r, message=FALSE, warning=FALSE}
state = "WISCONSIN"
lag = 60
plot_lag_interact(state, lag)
```

**9. run interactive time series plot with specified state and window
```{r, message=FALSE, warning=FALSE}
state = "FLORIDA"
window_num = 7
plot_time_interact(state, window_num)
```

