---
title: "Week10"
author: "Ben Yuan"
date: "11/5/2020"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, echo = FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(readr)
library(ggfortify)
library(ggseas)
```

## States Mask Order

```{r, message=FALSE, warning=FALSE, echo = FALSE}
data <- read_csv("covid.com.csv") %>% 
  select(c(-1))

# 15M stands for Mandatory Mask/Facecover Order
# See README of COVID_ALL_G1.xlsx
head(data[!is.na(data$EVENT_CATG_S) & data$EVENT_CATG_S == "15M",])
```

```{r, message=FALSE, warning=FALSE, echo = FALSE}
state1 = "Washington"
state2 = "Massachusetts"

state1_abb = state.abb[which(state.name == state1)]
state2_abb = state.abb[which(state.name == state2)]

state1_data <- data %>% 
  filter(STATE==toupper(state1)) %>% 
  select(c(3, 9, 14)) %>% 
  na.omit()

# if a state never issues mask order then plot all data
# else the plot starts at the day of mask order
state1_mask = which(!is.na(state1_data$EVENT_CATG_S) & state1_data$EVENT_CATG_S == "15M")
if(!identical(state1_mask, integer(0))){
  state1_data = state1_data[state1_mask:nrow(state1_data),]
} else{
  state1 = paste(state1, "(NO MASK ORDER)")
}


state2_data <- data %>% 
  filter(STATE==toupper(state2)) %>% 
  select(c(3, 9, 14)) %>% 
  na.omit()

state2_mask = which(!is.na(state2_data$EVENT_CATG_S) & state2_data$EVENT_CATG_S == "15M")
if(!identical(state2_mask, integer(0))){
  state2_data = state2_data[state2_mask:nrow(state2_data),]
} else{
  state2 = paste(state2, "(NO MASK ORDER)")
}


state1_data$DAYS = state1_data$DATE
state1_data$DAYS = as.numeric(state1_data$DATE-state1_data$DATE[1])
state2_data$DAYS = state2_data$DATE
state2_data$DAYS = as.numeric(state2_data$DATE-state2_data$DATE[1])

state1_color = "#FC4E07"
state2_color = "#00AFBB"

states_trend <- ggplot() +
  geom_line(data = state1_data, aes(x = DAYS, y = NEWCD_NORM_500), color = state1_color, size = 1.25) +
  geom_text(aes(x = tail(state1_data$DAYS, 1)+3, y = tail(state1_data$NEWCD_NORM_500, 1), label = state1_abb), color = state1_color) +
  geom_line(data = state2_data, aes(x = DAYS, y = NEWCD_NORM_500), color = state2_color, size = 1.25) +
  geom_text(aes(x = tail(state2_data$DAYS, 1)+3, y = tail(state2_data$NEWCD_NORM_500, 1), label = state2_abb), color = state2_color) +
  xlab("Number of Days Since Mask Order") + ylab("Normalized Daily New Cases") + ggtitle(paste("Mask Order in", state1, "and", state2))
  
states_trend
```


